server:
  port: 1200
spring:
  application:
    name: microservice-gateway-zuul
  zipkin:
    base-url: http://localhost:1500
  sleuth:
    sampler:
      percentage: 1.0
  rabbitmq:
    host: localhost
    port: 5672
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:1100/eureka/
  instance:
    ip-address: true
zuul:
  ignoredServices: '*'
  routes:
    test-rule:
      path: /path1/**
      serviceId: feign-consumer
    fallback-rule:
      path: /f/**
      serviceId: service-consumer
